CC = g++
CFLAGS=-c -Wall
LDFLAGS=
SOURCES=lcs.cpp
OBJECTS=$(SOURCES:.cpp=.o)
EXECUTABLE=lcs

all: $(SOURCES) $(EXECUTABLE)

$(EXECUTABLE): $(OBJECTS)
        $(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
        $(CC) $(CFLAGS) $< -o $@

